apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zsj37iqra-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zsj37iqra-go 
  name: zsj37iqra-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zsj37iqra-go 
